#!/bin/bash
echo "Installing dependencies..."

sudo apt install -y zsh bat tree python3-venv > /dev/null

if [ -d ~/.oh-my-zsh ]; then
  echo "oh-my-zsh already installed."
else
  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [ -d ~/.local/share/zinit ]; then
  echo "zinit already installed."
else
  echo "zinit not found, installing..."
  bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
fi

if [ -f /usr/bin/nvim ]; then
  echo "nvim already installed."
else
  echo "nvim not found, installing..."
  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  chmod u+x ./nvim.appimage
  sudo mv ./nvim.appimage /usr/bin/nvim
fi

if [ -d ~/.nvm ]; then
  echo "nvm already installed."
else
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi

sed -i '/zsh_custom_config/d' $HOME/.zshrc
echo 'source $HOME/.meine/zsh_custom_config.zsh' >> $HOME/.zshrc

echo "All done!"
