#!/bin/bash
echo "Installing dependencies..."

sudo apt install -y zsh bat vi tree python3-venv i3-wm perl libjson-perl > /dev/null
pip install --user i3-swallow

if [ -d ~/.oh-my-zsh ]; then
  echo "oh-my-zsh already installed."
else
  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if [ -d ~/.local/share/zinit ]; then
  echo "zinit already installed."
else
  echo "zinit not found, installing..."
  bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
fi

if [ -d /usr/bin/code ]; then
  echo "VS Code already installed."
else
  echo "Installing VS Code..."
  curl -o /tmp/code.deb -L https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
  sudo dpkg -i /tmp/code.deb
fi

if [ -d ~/.nvm ]; then
  echo "nvm already installed."
else
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
fi

sed -i '/zsh_custom_config/d' $HOME/.zshrc
echo 'source $HOME/.meine/zsh_custom_config.zsh' >> $HOME/.zshrc

echo "All done!"
